### ISSUE TITLE
change repository address

### ISSUE THREAD

**Issue by lidaobing** [jeffbyrnes/capistrano-scm-jenkins#26]
@jeffbyrnes can you move this project to your space.

I am no longer using or working on this project, and i think it's a good time for you to adopt this project. so can you move this project to your space, and I can help on all the issues you met (for example, setup a redirect README on this project, etc.)

thank you

**Comment by jeffbyrnes** [comment]
Sure thing! Lemme see about migrating it…

**Comment by jeffbyrnes** [comment]
@lidaobing so, as the owner, you need to transfer it to me. You can [read how in GitHub’s docs](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization).

**Comment by lidaobing** [comment]
@jeffbyrnes Done

**Comment by jeffbyrnes** [comment]
Great, thanks!
